### ISSUE TITLE
Can't run skeet test

### ISSUE THREAD

**Issue by euledge** [elsoul/skeet#105]
`skeet test` を実行しても何の結果も現れないという現象があります。
(自環境のせいなのかどうかはまだ特定できていません)
また同じ環境下で `yarn test` を実行した場合はテスト自体の実行はされますが、エラーになってしまいます。

skeet server 起動済
skeet loginで表示されている環境変数ACCESS_TOKENはコマンドライン上でexport 済

```
$export ACCESS_TOKEN=eyJhbGciOiJub.........
$ yarn test
yarn run v1.22.19
$ jest --coverage=false --detectOpenHandles --maxWorkers=1
 FAIL  tests/http/createUserChatRoom.test.ts
  ● POST without Bearer Token /createUserChatRoom › Responds with Auth Error

    SyntaxError: Unexpected token N in JSON at position 0
        at JSON.parse (<anonymous>)



  ● POST with Bearer Token /createUserChatRoom › Responds with Success

    SyntaxError: Unexpected token N in JSON at position 0
        at JSON.parse (<anonymous>)



 FAIL  tests/http/getUserChatRoomMessages.test.ts
  ● getUserChatRoomMessages › createUserChatRoom

    SyntaxError: Unexpected token N in JSON at position 0
        at JSON.parse (<anonymous>)



  ● getUserChatRoomMessages › addUserChatRoomMessage

    SyntaxError: Unexpected token N in JSON at position 0
        at JSON.parse (<anonymous>)



 FAIL  tests/http/addStreamUserChatRoomMessage.test.ts
  ● addStreamUserChatRoomMessage › createUserChatRoom

    SyntaxError: Unexpected token N in JSON at position 0
        at JSON.parse (<anonymous>)



  ● addStreamUserChatRoomMessage › addStreamUserChatRoomMessage

    SyntaxError: Unexpected token N in JSON at position 0
        at JSON.parse (<anonymous>)



 FAIL  tests/http/addUserChatRoomMessage.test.ts
  ● POST with Bearer Token /addUserChatRoomMessage › createUserChatRoom

    SyntaxError: Unexpected token N in JSON at position 0
        at JSON.parse (<anonymous>)



  ● POST with Bearer Token /addUserChatRoomMessage › addUserChatRoomMessage

    SyntaxError: Unexpected token N in JSON at position 0
        at JSON.parse (<anonymous>)



 PASS  tests/check.test.ts
  ● Console

    console.log
      OK

      at Object.<anonymous> (tests/check.test.ts:2:11)


Test Suites: 4 failed, 1 passed, 5 total
Tests:       8 failed, 1 passed, 9 total
Snapshots:   0 total
Time:        3.218 s, estimated 4 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by euledge** [comment]
コマンドラインでの環境変数に PROJECT_IDとREGIONを追加した実行結果です。

```
$ yarn test
yarn run v1.22.19
$ jest --coverage=false --detectOpenHandles --maxWorkers=1
 FAIL  tests/http/createUserChatRoom.test.ts
  ● POST with Bearer Token /createUserChatRoom › Responds with Success

    expect(received).toEqual(expected) // deep equality

    Expected: 200
    Received: 500

      37 |     )
      38 |     const data = await response.json()
    > 39 |     expect(response.status).toEqual(200)
         |                             ^
      40 |     expect(data).toEqual(
      41 |       expect.objectContaining({
      42 |         status: 'success',

      at tests/http/createUserChatRoom.test.ts:39:29
      at step (tests/http/createUserChatRoom.test.ts:33:23)
      at Object.next (tests/http/createUserChatRoom.test.ts:14:53)
      at fulfilled (tests/http/createUserChatRoom.test.ts:5:58)

 FAIL  tests/http/addUserChatRoomMessage.test.ts
  ● POST with Bearer Token /addUserChatRoomMessage › createUserChatRoom

    expect(received).toEqual(expected) // deep equality

    Expected: 200
    Received: 500

      21 |     )
      22 |     const data = await response.json()
    > 23 |     expect(response.status).toEqual(200)
         |                             ^
      24 |     expect(data).toEqual(
      25 |       expect.objectContaining({
      26 |         status: 'success',

      at tests/http/addUserChatRoomMessage.test.ts:23:29
      at step (tests/http/addUserChatRoomMessage.test.ts:33:23)
      at Object.next (tests/http/addUserChatRoomMessage.test.ts:14:53)
      at fulfilled (tests/http/addUserChatRoomMessage.test.ts:5:58)

  ● POST with Bearer Token /addUserChatRoomMessage › addUserChatRoomMessage

    expect(received).toEqual(expected) // deep equality

    Expected: 200
    Received: 500

      44 |     )
      45 |     const data = await response.json()
    > 46 |     expect(response.status).toEqual(200)
         |                             ^
      47 |     expect(data).toEqual(
      48 |       expect.objectContaining({
      49 |         status: 'success',

      at tests/http/addUserChatRoomMessage.test.ts:46:29
      at step (tests/http/addUserChatRoomMessage.test.ts:33:23)
      at Object.next (tests/http/addUserChatRoomMessage.test.ts:14:53)
      at fulfilled (tests/http/addUserChatRoomMessage.test.ts:5:58)

 FAIL  tests/http/addStreamUserChatRoomMessage.test.ts
  ● addStreamUserChatRoomMessage › createUserChatRoom

    expect(received).toEqual(expected) // deep equality

    Expected: 200
    Received: 500

      20 |     )
      21 |     const data = await response.json()
    > 22 |     expect(response.status).toEqual(200)
         |                             ^
      23 |     expect(data).toEqual(
      24 |       expect.objectContaining({
      25 |         status: 'success',

      at tests/http/addStreamUserChatRoomMessage.test.ts:22:29
      at step (tests/http/addStreamUserChatRoomMessage.test.ts:33:23)
      at Object.next (tests/http/addStreamUserChatRoomMessage.test.ts:14:53)
      at fulfilled (tests/http/addStreamUserChatRoomMessage.test.ts:5:58)

  ● addStreamUserChatRoomMessage › addStreamUserChatRoomMessage

    expect(received).toEqual(expected) // deep equality

    Expected: 200
    Received: 500

      43 |     )
      44 |     const data = await response.json()
    > 45 |     expect(response.status).toEqual(200)
         |                             ^
      46 |     expect(data).toEqual(
      47 |       expect.objectContaining({
      48 |         status: 'streaming',

      at tests/http/addStreamUserChatRoomMessage.test.ts:45:29
      at step (tests/http/addStreamUserChatRoomMessage.test.ts:33:23)
      at Object.next (tests/http/addStreamUserChatRoomMessage.test.ts:14:53)
      at fulfilled (tests/http/addStreamUserChatRoomMessage.test.ts:5:58)

 FAIL  tests/http/getUserChatRoomMessages.test.ts
  ● getUserChatRoomMessages › createUserChatRoom

    expect(received).toEqual(expected) // deep equality

    Expected: 200
    Received: 500

      20 |     )
      21 |     const data = await response.json()
    > 22 |     expect(response.status).toEqual(200)
         |                             ^
      23 |     expect(data).toEqual(
      24 |       expect.objectContaining({
      25 |         status: 'success',

      at tests/http/getUserChatRoomMessages.test.ts:22:29
      at step (tests/http/getUserChatRoomMessages.test.ts:33:23)
      at Object.next (tests/http/getUserChatRoomMessages.test.ts:14:53)
      at fulfilled (tests/http/getUserChatRoomMessages.test.ts:5:58)

  ● getUserChatRoomMessages › addUserChatRoomMessage

    expect(received).toEqual(expected) // deep equality

    Expected: 200
    Received: 500

      43 |     )
      44 |     const data = await response.json()
    > 45 |     expect(response.status).toEqual(200)
         |                             ^
      46 |     expect(data).toEqual(
      47 |       expect.objectContaining({
      48 |         status: 'success',

      at tests/http/getUserChatRoomMessages.test.ts:45:29
      at step (tests/http/getUserChatRoomMessages.test.ts:33:23)
      at Object.next (tests/http/getUserChatRoomMessages.test.ts:14:53)
      at fulfilled (tests/http/getUserChatRoomMessages.test.ts:5:58)

 PASS  tests/check.test.ts
  ● Console

    console.log
      OK

      at Object.<anonymous> (tests/check.test.ts:2:11)


Test Suites: 4 failed, 1 passed, 5 total
Tests:       7 failed, 2 passed, 9 total
Snapshots:   0 total
Time:        3.327 s, estimated 4 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by euledge** [comment]
API側 try catch の catchでエラーを表示しましたが以下のようなエラーになっていました

```
22:37:04 I function[asia-northeast1-createUserChatRoom] Beginning execution of "asia-northeast1-createUserChatRoom"
22:37:04 I function[asia-northeast1-createUserChatRoom] Error: getUserAuth: Error: Invalid token!
```
テストのときはログインされていない状態であるので、何らかの方法でログイン済であるようにしないとこのテストはエラーになるように思えますがいかがでしょうか？

気になってCI/CDのGithubActionを見ましたが簡易的なテストのcheck.test.tsのみが実行されておりましたので
おそらくこれについては既知のものではないか推察しますが、あっていますでしょうか？
そうであれば、いったん深追いせずに終了したいと思います。

**Comment by euledge** [comment]
提案ですが、firebase functionについてのテストは実際にPOSTせずにメソッドのテストするという方法はどうでしょうか?
Mockも効きそうですし、http function以外のpubsub,firestore,authなどもテスト可能になると思います。

https://firebase.google.com/docs/functions/unit-testing?hl=ja

**Comment by POPPIN-FUMI** [comment]
@euledge ありがとうございます！ skeet test コマンドはまだ実装前のものが表に出てしまっていました！
一旦、skeet testコマンドは消しておきます。

おっしゃる通り、テストの方法から構成を変更していこうと考えていました。
Skeet Frameworkのバックエンドでは関数の定義は functions/<function>/src/lib/ 内に skeet ai の method モードで作成されるように
なります。Firebase でのインスタンスは lib から関数を使用するので、
lib の関数のテストと functions/<function>/src/rountings/ 内の Firebase Functions のテストが必要だと思っていました！
もしアイデアが既にございましたら、是非PRの方お願いします☺️
