### ISSUE TITLE
skeet yarn i fail with solana-mobile-stack template

### ISSUE THREAD

**Issue by KishiTheMechanic** [elsoul/skeet#203]
```
➜  skeet-solana-mobile-stack git:(main) ✗ skeet yarn i
Error getting function directories: Error: ENOENT: no such file or directory, stat 'functions/skeet/node_modules/@skeet-framework/firestore/node_modules/@firebase/firestore/node_modules/.bin/proto-loader-gen-types'
    at statSync (node:fs:1676:25)
    at /Users/ktm/.anyenv/envs/nodenv/versions/20.10.0/lib/node_modules/@skeet-framework/cli/dist/index.js:1243:912
    at Array.forEach (<anonymous>)
    at getDirectoryLastModified (/Users/ktm/.anyenv/envs/nodenv/versions/20.10.0/lib/node_modules/@skeet-framework/cli/dist/index.js:1243:864)
    at /Users/ktm/.anyenv/envs/nodenv/versions/20.10.0/lib/node_modules/@skeet-framework/cli/dist/index.js:1243:942
    at Array.forEach (<anonymous>)
    at getDirectoryLastModified (/Users/ktm/.anyenv/envs/nodenv/versions/20.10.0/lib/node_modules/@skeet-framework/cli/dist/index.js:1243:864)
    at /Users/ktm/.anyenv/envs/nodenv/versions/20.10.0/lib/node_modules/@skeet-framework/cli/dist/index.js:1243:942
    at Array.forEach (<anonymous>)
    at getDirectoryLastModified (/Users/ktm/.anyenv/envs/nodenv/versions/20.10.0/lib/node_modules/@skeet-framework/cli/dist/index.js:1243:864) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'functions/skeet/node_modules/@skeet-framework/firestore/node_modules/@firebase/firestore/node_modules/.bin/proto-loader-gen-types'
}
? Select Services to run yarn command (Press <space> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)
  = Services = 
❯◯ webapp
 ◯ root
```

**Comment by POPPIN-FUMI** [comment]
`rm -rf functions/skeet/node_modules` and `yarn --cwd functions/skeet install`
