### ISSUE TITLE
skeet sync routing broken

### ISSUE THREAD

**Issue by KishiTheMechanic** [elsoul/skeet#362]
Add await to createNeg but didn't solve it.

```
➜  epics-platform git:(bdlc/staking) skeet sync routing
 ⌛ syncRoutings... ⠇Error executing command: Error: Command failed with code 1: ERROR: (gcloud.compute.network-endpoint-groups.describe) Could not fetch resource:
 - The resource 'projects/epics-platform/regions/asia-northeast1/networkEndpointGroups/skeet-redeem-staking-bdlcrewards-neg' was not found


    at ChildProcess.<anonymous> (file:///Users/ktm/Library/pnpm/global/5/.pnpm/@skeet-framework+cli@2.2.1/node_modules/@skeet-framework/cli/dist/index.js:873:4237)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
 ⌛ syncRoutings... ⠼Error executing command: Error: Command failed with code 1: ERROR: (gcloud.compute.network-endpoint-groups.describe) Could not fetch resource:
 - The resource 'projects/epics-platform/regions/asia-northeast1/networkEndpointGroups/skeet-unstake-bdlc-neg' was not found


    at ChildProcess.<anonymous> (file:///Users/ktm/Library/pnpm/global/5/.pnpm/@skeet-framework+cli@2.2.1/node_modules/@skeet-framework/cli/dist/index.js:873:4237)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
 ⌛ syncRoutings... ⠙Error executing command: Error: Command failed with code 1: ERROR: (gcloud.compute.network-endpoint-groups.describe) Could not fetch resource:
 - The resource 'projects/epics-platform/regions/asia-northeast1/networkEndpointGroups/skeet-update-stake-record-neg' was not found


    at ChildProcess.<anonymous> (file:///Users/ktm/Library/pnpm/global/5/.pnpm/@skeet-framework+cli@2.2.1/node_modules/@skeet-framework/cli/dist/index.js:873:4237)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
 ⌛ syncRoutings... ⠏Error executing command: Error: Command failed with code 1: ERROR: (gcloud.compute.network-endpoint-groups.describe) Could not fetch resource:
 - The resource 'projects/epics-platform/regions/asia-northeast1/networkEndpointGroups/skeet-staking-db-neg' was not found


    at ChildProcess.<anonymous> (file:///Users/ktm/Library/pnpm/global/5/.pnpm/@skeet-framework+cli@2.2.1/node_modules/@skeet-framework/cli/dist/index.js:873:4237)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
 ⌛ syncRoutings... ⠸Error executing command: Error: Command failed with code 1: ERROR: (gcloud.compute.network-endpoint-groups.describe) Could not fetch resource:
 - The resource 'projects/epics-platform/regions/asia-northeast1/networkEndpointGroups/skeet-card-db-neg' was not found


    at ChildProcess.<anonymous> (file:///Users/ktm/Library/pnpm/global/5/.pnpm/@skeet-framework+cli@2.2.1/node_modules/@skeet-framework/cli/dist/index.js:873:4237)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
 ⌛ syncRoutings... ⠴Error executing command: Error: Command failed with code 1: ERROR: (gcloud.compute.url-maps.add-path-matcher) No host rule with host [undefined] exists. Check your spelling or use [--new-hosts] to create a new host rule.

    at ChildProcess.<anonymous> (file:///Users/ktm/Library/pnpm/global/5/.pnpm/@skeet-framework+cli@2.2.1/node_modules/@skeet-framework/cli/dist/index.js:873:4237)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

neg has not be created.

If neg exists, bs has not be created.

Async / Await problem? I didn't know

**Comment by POPPIN-FUMI** [comment]
`skeet-cloud.config.json`
changed key name `rountings` to `rounting` for v3
