### ISSUE TITLE
Couldn't use `addStreamUserChatRoomMessage` function on Tutorial

### ISSUE THREAD

**Issue by KishiTheMechanic** [elsoul/skeet#5]
```
skeet-test-app git:(main) ✗ skeet curl addStreamUserChatRoomMessage --data '{ "userChatRoomId": "f2biuil3L6k0EdHzxMTl", "content": "Do some freestyle rap" }'

{
  production: false,
  functions: false,
  data: '{ "userChatRoomId": "f2biuil3L6k0EdHzxMTl", "content": "Do some freestyle rap" }'
}
curl --location --request POST http://127.0.0.1:5001/skeet-test-app/europe-west6/addStreamUserChatRoomMessage --data '{ "userChatRoomId": "f2biuil3L6k0EdHzxMTl", "content": "Do some freestyle rap" }' --header 'Content-Type: application/json' --header "Authorization: Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJlbWFpbCI6ImVwaWNzZGFvQGVwaWNzLmRldiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiYXV0aF90aW1lIjoxNjg0OTcwMjMzLCJ1c2VyX2lkIjoidmVtZWtiNHJVcDE3MDdRc1NoNzBPWmpHbUliRiIsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZXBpY3NkYW9AZXBpY3MuZGV2Il19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifSwiaWF0IjoxNjg0OTcwMjMzLCJleHAiOjE2ODQ5NzM4MzMsImF1ZCI6InNrZWV0LXRlc3QtYXBwIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL3NrZWV0LXRlc3QtYXBwIiwic3ViIjoidmVtZWtiNHJVcDE3MDdRc1NoNzBPWmpHbUliRiJ9." | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   326  100   246  100    80  74613  24264 --:--:-- --:--:-- --:--:--  318k
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "Function europe-west...") at /usr/bin/json_pp5.30 line 52.
Error: curl: Error: Command failed: curl --location --request POST http://127.0.0.1:5001/skeet-test-app/europe-west6/addStreamUserChatRoomMessage --data '{ "userChatRoomId": "f2biuil3L6k0EdHzxMTl", "content": "Do some freestyle rap" }' --header 'Content-Type: application/json' --header "Authorization: Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJlbWFpbCI6ImVwaWNzZGFvQGVwaWNzLmRldiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiYXV0aF90aW1lIjoxNjg0OTcwMjMzLCJ1c2VyX2lkIjoidmVtZWtiNHJVcDE3MDdRc1NoNzBPWmpHbUliRiIsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZXBpY3NkYW9AZXBpY3MuZGV2Il19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifSwiaWF0IjoxNjg0OTcwMjMzLCJleHAiOjE2ODQ5NzM4MzMsImF1ZCI6InNrZWV0LXRlc3QtYXBwIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL3NrZWV0LXRlc3QtYXBwIiwic3ViIjoidmVtZWtiNHJVcDE3MDdRc1NoNzBPWmpHbUliRiJ9." | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   326  100   246  100    80  74613  24264 --:--:-- --:--:-- --:--:--  318k
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "Function europe-west...") at /usr/bin/json_pp5.30 line 52.

    at J3 (/Users/ktm/.anyenv/envs/nodenv/versions/18.16.0/lib/node_modules/@skeet-framework/cli/dist/index.js:397:746)
    at Ss.<anonymous> (/Users/ktm/.anyenv/envs/nodenv/versions/18.16.0/lib/node_modules/@skeet-framework/cli/dist/index.js:408:4052)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Ss.parseAsync (/Users/ktm/.anyenv/envs/nodenv/versions/18.16.0/lib/node_modules/@skeet-framework/cli/dist/index.js:15:4063)
    at async r3e (/Users/ktm/.anyenv/envs/nodenv/versions/18.16.0/lib/node_modules/@skeet-framework/cli/dist/index.js:408:4096)
```

**Comment by POPPIN-FUMI** [comment]
fixed
