### ISSUE TITLE
error when running `skeet --version` on version 1.5.9 and above

### ISSUE THREAD

**Issue by euledge** [elsoul/skeet#90]
skeet-cli のバージョンを上げたたのですが、実行時にエラーが表示されます。
version 1.5.9 以降で発生しています

```
$ skeet --version
1.5.8

$ sudo npm i -g @skeet-framework/cli@1.5.9

changed 577 packages in 16s

54 packages are looking for funding
  run `npm fund` for details

$ skeet --version
Error: ENOENT: no such file or directory, scandir './functions/skeet/src/models'
    at readdirSync (node:fs:1527:3)
    at WXo (/usr/local/share/npm-global/lib/node_modules/@skeet-framework/cli/dist/index.js:502:1204)
    at /usr/local/share/npm-global/lib/node_modules/@skeet-framework/cli/dist/index.js:509:33
    at /usr/local/share/npm-global/lib/node_modules/@skeet-framework/cli/dist/index.js:2:263
    at /usr/local/share/npm-global/lib/node_modules/@skeet-framework/cli/dist/index.js:583:359
    at /usr/local/share/npm-global/lib/node_modules/@skeet-framework/cli/dist/index.js:2:263
    at /usr/local/share/npm-global/lib/node_modules/@skeet-framework/cli/dist/index.js:837:1221
    at /usr/local/share/npm-global/lib/node_modules/@skeet-framework/cli/dist/index.js:2:263
    at /usr/local/share/npm-global/lib/node_modules/@skeet-framework/cli/dist/index.js:837:4724
    at /usr/local/share/npm-global/lib/node_modules/@skeet-framework/cli/dist/index.js:2:263 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: './functions/skeet/src/models'
}
1.5.9
```

**Comment by KishiTheMechanic** [comment]
ご報告ありがとうございます！
こちらver1.6.4にてfixいたしました！
ぜひバージョンの方上げてお試しいただければ幸いです🙏

いつもありがとうございます！

**Comment by euledge** [comment]
@KishiTheMechanic 
ver1.6.4でエラーが出ないこと 確認いたしました。
いつも修正の対応が早くて助かります。

**Comment by KishiTheMechanic** [comment]
こちらこそいつもありがとうございます！
また何かお気づきの点があればissueの方立ち上げていただければ大変助かります！

引き続きよろしくお願いいたします🙌
